language: java

os: linux
jdk: openjdk8
dist: trusty

before_deploy:
  - ./gradlew clean
  - ./gradlew jar

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "build/libs/*"
  skip_cleanup: true
  name: Gradel Test compile
  tag: beta
  on:
    all_branches: true
#    tags: true