language: java

jdk:
  - oraclejdk8
  - oraclejdk14
  - openjdk8
  - openjdk14

dist: trusty

script:
  - ./gradlew clean
  - ./gradlew jar

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "build/libs/*"
  on:
    all_branches: true
    tags: true