language: java

os: linux
jdk: openjdk8
dist: trusty

script:
  - ./gradlew clean
  - ./gradlew jar

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "build/libs/*"
  name: Gradle Test
  cleaup: false
  on:
    all_branches: true
    tags: true