language: java

script:
  - ./gradlew jar

deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "TestFile.jar"
  on:
    all_branches: true
    tags: true